### PR TITLE
Drop EoL Ruby 2.5 support; require 3.2

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by LukasAud** [comment]
Hey @bastelfreak, unfortunately we won't be able to merge this one. We officially support Ruby 2.x (technically only 2.7), and as such, we have to ensure we are testing against it. I will look into raising that 2.5 value into a 2.7 so that we are not testing against EOL.

**Comment by bastelfreak** [comment]
2.7 is EoL as well. Why do you have to support that version?

**Comment by LukasAud** [comment]
Hey @bastelfreak. We always support two Puppet Enterprise releases, latest and LTS (the previous one). When we do this, we also commit to ensure that all our tooling and modules are compatible with both releases. That includes ensuring that relevant packages, technologies, dependencies, etc are being properly tested and maintained. Since PE LTS works on Puppet 7 and Puppet 7 works on Ruby 2.7, we have to maintain infrastructure around it.

**Comment by bastelfreak** [comment]
But Puppet 7 and Puppt 8 don't rely on gettext-setup? So what exactly is blocking this update? And even if there's something that depends on gettext-setup that needs to stay compatible with Ruby 2.7, what's the problem? Dropping support for a major Ruby version should trigger a new major release. So gettext-setup 2. And Other tools shouldn't automatically pull major releases. So What exactly is the fear here?

**Comment by LukasAud** [comment]
Where possible, we commit to make sure all new releases for tools, modules and gems we maintain are compatible with both versions. That includes testing. If we release a 2.0 that removes Ruby 2.x testing, then we cannot ensure that future updates will not break the code for the older version.

As for Puppet 7/8 consumption of this gem, we are currently investigating if it has relevant use anymore. But there are a few examples of it being imported/called in repos like [puppet](https://github.com/puppetlabs/puppet/blob/main/Gemfile#L76) and [puppet-runtime](https://github.com/puppetlabs/puppet-runtime/blob/08c0261f9425ac494c033b36859b5240403293f1/configs/components/rubygem-gettext-setup.rb#L2) or [r10k](https://github.com/puppetlabs/r10k/blob/8dd238fe3d3a4c69386348c73f5b8fca001b72fd/r10k.gemspec#L33).

**Comment by LukasAud** [comment]
It might also be worth mentioning that there is also a large enough amount of people still using Puppet 7 (some even older versions) for us to be serious about maintaining its support and providing them with the same versions we offer Puppet 8 users until the end of its lifespan (normally, around the time Puppet 9 comes into play)

**Comment by LukasAud** [comment]
Hey @bastelfreak, as previously mentioned, we will not be dropping Ruby 2.x testing as we commit to offering support for it for as long as Puppet 7 is still supported. Therefore, I will be closing this PR.

If you have any strong opinions against this decision, feel free to reopen this PR or to create a new discussion in the 'Issues' tab. Alternatively, you can also ask us more about this topic during Office hours.

**Pull request closed without merging**
