### PR TITLE
(MAINT) fixed broken link, etc.

### PR DESCRIPTION
**Pull request by ehom**
* fixed broken link to sinatrarb.com. also, added a comma after "By default" for easier reading.
* fixed minor issue in ordered list. also, removed explicit line breaks so that the browser can do the line wrapping.
* moved single line of ruby code into code block 
* added code block for string resources being used in pluralization explanation

### CODE REVIEW

**Comment by smcclellan** [comment]
Thanks for these fixes. Where did the `>= 2.1.0` come from? I don't see that in the `.rubocop.yml` file, and as far as I know we're still trying to support 1.9.3.

**Comment by Magisus** [comment]
We definitely need to still support 1.9.3, because of our being stuck on JRuby 1.7 for the time being.

**Comment by ehom** [comment]
will post error message shortly

**Comment by smcclellan** [comment]
I see the error:

```
Offenses:
gettext-setup.gemspec:18:32: C: Gemspec/RequiredRubyVersion: required_ruby_version (1.9, declared in gettext-setup.gemspec) and TargetRubyVersion (2.1, declared in .rubocop.yml) should be equal.
  spec.required_ruby_version = '>= 1.9.2'
                               ^^^^^^^^^^
15 files inspected, 1 offense detected
```

I think we want to change the other value then, I'll look for where that's actually defined.

**Comment by smcclellan** [comment]
@ehom I've fixed that ruby version issue in [a separate PR/commit](https://github.com/puppetlabs/gettext-setup-gem/pull/59). If you rebase to `master`, Travis should run just fine. Could you drop the commit for `required_ruby_version` from this PR? I'll also squash the four documentation-based commits into one commit when I merge.

**Comment by ehom** [comment]
@smcclellan I went ahead and reverted my last change. I hope that was the right way to do it.

**Comment by smcclellan** [comment]
That will work in this case since I'm just going to squash all commits into the same one. In the future, it's usually best to amend the commit and force-push to your local branch. Thanks for these changes!

**Pull request merged**
